### ISSUE TITLE
read_csv and read_table fail with some CSV files. May be related to universal-newline

### ISSUE THREAD

**Issue by aullrich2013** [pandas-dev/pandas#9045]
Using pandas 0.15.1
I have a csv file which unfortunately I cannot share (sanitizing it resolved the error) that gives me trouble when reading using the default (c) engine for parsing files. I switched to the python version which also failed but gave me the hint that it might be a problem with "universal-newline". 
If I pass a file buffer instead that was opened with the universal-newline option then all works as expected. 
This is the error I receive:

```
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python(732,0x7fff7bc25300) malloc: *** mach_vm_map(size=18446744071562067968) failed (error code=3)
```

I've narrowed it down to the following (commented) interactions:

```
filePath = '/Volumes/Macintosh HD/data/FPGA Compile Cloud/aug14-nov14.csv'
fUniv = open(filePath, 'U')
f = open(filePath)
d = pd.read_csv(filePath,parse_dates=False, engine='c') # kernel restarts or malloc region error continuously and must be manually killed
d = pd.read_csv(f,parse_dates=False, engine='c') # kernel restarts or malloc region error continuously and must be manually killed
d = pd.read_csv(f,parse_dates=False, engine='python') # gives universal-newline error when passing file handle or filePath
d = pd.read_csv(fUniv,parse_dates=False, engine='c') # reads the dataframe correctly
```

This is my installed software:
anyreadline (0.1.1)
apptools (4.2.0)
argcomplete (0.6.7)
astropy (0.3.2)
atom (0.3.7)
awake (1.0)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.3.1)
binstar (0.5.3)
biopython (1.62)
bitarray (0.8.1)
blaze (0.5)
blz (0.6.2)
bokeh (0.4.4)
boto (2.28.0)
brewer2mpl (1.4)
casuarius (1.1)
cdecimal (2.3)
chaco (4.4.1)
colorama (0.2.5)
conda (3.5.5)
configobj (5.0.5)
cubes (0.10.2)
Cython (0.20.1)
DataShape (0.2)
dill (0.2b1)
distribute (0.6.45)
Django (1.5.4)
docutils (0.11)
enable (4.3.0)
enaml (0.9.1)
envisage (4.3.0)
Flask (0.9)
Flask-KVSession (0.3.2)
future (0.12.1)
gevent (1.0.1)
gevent-websocket (0.9.3)
gevent-zeromq (0.2.2)
ggplot (0.5.8)
gnureadline (6.3.3)
google-api-python-client (1.1)
greenlet (0.4.2)
grin (1.2.1)
guppy (0.1.10)
h5py (2.3.0)
httplib2 (0.8)
icalendar (3.5)
ipdb (0.8)
ipython (2.3.1)
iso8601 (0.1.10)
itsdangerous (0.24)
jdcal (1.0)
Jinja2 (2.7.3)
keyring (3.2)
kiwisolver (0.1.2)
line-profiler (1.0b3)
llvmmath (0.1)
llvmpy (0.12.6)
lxml (3.3.5)
MarkupSafe (0.23)
matplotlib (1.3.1)
matplotlylib (0.1.0)
mayavi (4.3.0)
MDP (3.3)
memory-profiler (0.31)
meta (development)
mock (1.0.1)
multipledispatch (0.4.3)
netCDF4 (1.0.6)
networkx (1.8.1)
nltk (2.0.4)
nose (1.3.3)
numba (0.13.2)
numexpr (2.3.1)
numpy (1.9.1)
numpydoc (0.4)
openpyxl (1.8.5)
pandas (0.15.1)
patsy (0.2.1)
pep8 (1.5.6)
PIL (1.1.7)
pip (1.5.2)
plotly (1.4.0)
ply (3.4)
prettytable (0.7.2)
progressbar (2.2)
psutil (2.1.1)
py (1.4.20)
PyAudio (0.2.7)
pycosat (0.6.1)
pycparser (2.10)
pycrypto (2.6.1)
pycurl (7.19.3.1)
pydot (1.0.2)
pyface (4.4.0)
pyflakes (0.8.1)
Pygments (1.6)
pykit (0.1)
pylev (1.2.0)
pypandoc (0.8.1)
pyparsing (1.5.7)
PySAL (1.6.0)
pysam (0.6)
pytest (2.5.2)
python-dateutil (2.3)
python-gflags (2.0)
pytz (2014.10)
pyxDamerauLevenshtein (1.1)
PyYAML (3.11)
pyzmq (14.3.1)
qgrid (0.1.1)
redis (2.9.1)
requests (2.3.0)
rope (0.9.4)
runipy (0.1.1)
scikit-image (0.10.1)
scikit-learn (0.15.2)
scipy (0.14.0)
selenium (2.44.0)
setuptools (0.6c11)
simplekv (0.9.2)
six (1.8.0)
sklearn-compiledtrees (1.2)
Sphinx (1.2.2)
spyder (2.3.0rc)
SQLAlchemy (0.9.4)
statsmodels (0.5.0)
sympy (0.7.5)
tables (3.1.1)
tornado (3.2.1)
traits (4.4.0)
traitsui (4.4.0)
ujson (1.33)
VTK (5.10.1)
websocket-client (0.12.0)
Werkzeug (0.9.6)
wsgiref (0.1.2)
xlrd (0.9.3)
XlsxWriter (0.5.5)
xlwt (0.7.5)
yhat (0.7.5)

**Comment by qudade** [comment]
I think this issue can be closed?

**Comment by jbrockmendel** [comment]
@aullrich2013 Closing this as stale, but if you can post an example we can copy/paste (see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) we can reopen and take a look at it.
