### ISSUE TITLE
Feature request: Categorical plotting

### ISSUE THREAD

**Issue by michaelaye** [pandas-dev/pandas#9069]
In the case of the index being a DateTimeIndex, I think there's a nice easy default case for plotting a categorical column: Let each category assume one value on the y-axis (user-providable, or range(len(categories)) by default) and plot a symbol ('*' by default maybe) at every point in time the categorical value has an entry. The y-axis tick labels should be the categorical values of course.
This can provide nice overviews in astronomy or other remote sensing sciences for example to indicate what kind of observation happened when and in what sequence. Or which of some set of lab experiments was executed when.

What do you guys think?

**Comment by shoyer** [comment]
It looks like `seaborn.stripplot` will handle plotting categorical data along one axis: https://github.com/mwaskom/seaborn/pull/410

**Comment by jreback** [comment]
looks sexy!

**Comment by TomAugspurger** [comment]
Going to close this in favor of more specific issues. The basics are working now (bar and scatter).
