### ISSUE TITLE
Problem assigning values to a 1d slice of Panel with MultiIndex along major axis

### ISSUE THREAD

**Issue by eoincondron** [pandas-dev/pandas#9080]
I've encountered a problem when using .loc and .iloc to assign values to a 1D slice of a Panel when the axis in the direction of the slice has a MulitIndex. Here is a simple example to demonstrate:

```
import pandas as pd
import numpy as np
pn = pd.Panel(np.zeros((3, 3, 3)))
pn.loc[0, :, 0] = [1, 2, 3]
pn.major_axis = pd.MultiIndex.from_tuples(zip([1, 2, 3], list('abc')))
pn.loc[0, :, 0] = [1, 2, 3]
```

Running this code gives an IndexError at the last line with the message 'tuple index out of range'.
Note how the error is only raised after the major axis has been set with the MulitIndex.
Using .iloc or .ix instead produces the same error. A similar procedure using either of the other two axes produces no error. Pandas version is 0.15.1

**Comment by jreback** [comment]
closing as Panels are deprecated
