### ISSUE TITLE
SQL: test with oldest supported sqlalchemy

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#9087]
Noticed when looking at #9083 that we used an sqlalchemy feature in #8926 that is not supported in at least sqlalchemy 

Concrete, it is about `import sqlalchemy.sql.type_api as type_api` (https://github.com/pydata/pandas/blob/v0.15.2/pandas/io/sql.py#L1162). I cannot import this 0.8.2 (and in any case, this should better be `sqlalchemy.types.TypeEngine` instead of `type_api.TypeEngine`)

We should check if we test older slqalchemy versions (0.8.x series, or even 0.7.x series?), or why this has not been caught by the tests.

**Comment by jbrockmendel** [comment]
@datapythonista i know you've been looking at the dependencies in the CI.  is this feasible?

**Comment by datapythonista** [comment]
I'll make a proposal soon for #29685, which should fix this sort of problems.

But this issue is 5 years old, I assume this is not a problem anymore. Closing.
