### ISSUE TITLE
[Feature Request] Add concise xlabel=, ylabel=, option in plot() method

### ISSUE THREAD

**Issue by xgdgsc** [pandas-dev/pandas#9093]
The current [plot()](http://pandas.pydata.org/pandas-docs/version/0.15.1/generated/pandas.DataFrame.plot.html#pandas.DataFrame.plot) method for Dataframe cannot set the x/y label in it. [Result](http://stackoverflow.com/questions/21487329/add-x-and-y-labels-to-a-pandas-plot?lq=1) is more lines of code for just doing this. 

As someone commented in that post:

> Is there a particular reason why x and y labels can't be added as arguments to pd.plot()? Given the additional concision of pd.plot() over plt.plot() it seems it would make sense to make it even more succinct instead of having to call ax.set_ylabel()

**Comment by ispmarin** [comment]
:+1:

**Comment by roryhr** [comment]
Scientists are taught always include a title and labelled axes on plots. Ideally, the Pandas default plot command would intelligently title and label plots. This is an important issue because adding labels to plots is still too difficult.

**Comment by TomAugspurger** [comment]
Pandas grabs index name automatically for the x axis, and adds legends automatically. The issue isn't the defaults, it's the lack of an option for overriding those defaults. I think we're open to adding these arguments if someone has the time to submit a pull request.

**Comment by roryhr** [comment]
Sounds good. I'll take a look and see what I can do.

**Comment by paulbalegend** [comment]
Any activity on this?  I would like to add a vote for this feature.

I think it would make most sense if the default behavior was to intelligently set ylabels--regardless of if it's a standard plot, a `subplots=True` plot, a `secondary_y=whatever` plot--instead of the way it automatically inserts a legend in all of these cases.

**Comment by TomAugspurger** [comment]
I'd recommend staring small and just add support for overriding the default
xlablel / ylabel.
