### ISSUE TITLE
TST: start testing with SQL server via appveyor CI

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#9097]
http://www.appveyor.com/docs/services-databases

We could add tests for SQL Server to test_sql.py, as AppVeyor supports this.

**Comment by jbrockmendel** [comment]
@jorisvandenbossche do you think this is still worth pursuing since we no longer use appveyor?  I dont know how common a use case sql server is (or if we ca do it via travis/azure)

**Comment by jbrockmendel** [comment]
Closing since we no longer use appveyor.  Feel free to re-open (and re-title) if you think it applies to Travis or Azure

**Comment by jorisvandenbossche** [comment]
I assume that testing on Windows with SQL Server on Azure or Github actions could still be useful, but also not something that is highly needed (nor something I would plan to work on myself)
