### ISSUE TITLE
read_excel drops columns when reading a one row file with a MultiIndex

### ISSUE THREAD

**Issue by maxgrenderjones** [pandas-dev/pandas#9208]
I'm seeing the weirdest error.

When I read an .xlsx excel file with only one row (example below)...
![image](https://cloud.githubusercontent.com/assets/6059365/5653615/b8ae57ca-96b3-11e4-8a9d-25e716d2a122.png)
... and try to set the `index_col`, then pandas incorrectly reads the columns:

I.e. for a file with only one row, column headers A, B, C, D, E, F

``` python
pandas.read_excel(filename, 'Sheet1', index_col=['A', 'B', 'C'])
```

Yields
![image](https://cloud.githubusercontent.com/assets/6059365/5653647/0f8f049a-96b4-11e4-89bc-6d5d355dbde8.png)
(I get an index with columns A, B, C, and a dataframe with columns B, D, F - what happened to E?)

Note that if I don't use `index_col`, I get a dataframe with columns A-F as expected. Likewise, if I add a row of actual data, the dataframe loads as expected.

Relevant versions:
`pandas version 0.15.1 running on 2.7.7 |Anaconda 2.0.1 (64-bit)| (default, Jun 11 2014, 10:40:02) [MSC v.1500 64 bit (AMD64)]`
`xlrd.__VERSION__`=0.9.3

**Comment by jorisvandenbossche** [comment]
I can confirm this with 0.15.2

**Comment by maxgrenderjones** [comment]
Would have to dig into it (unlikely to have time soon), but #10184 might suggest how this could be fixed, as the issues seem similar.
