### ISSUE TITLE
drop_duplicates() on a float64 type column containing NaN values will cause CPU 100% occupied forever

### ISSUE THREAD

**Issue by scratdata** [pandas-dev/pandas#9211]
I'm using 0.15.0 version, and I find when I apply drop_duplicates() on "PostCode" column, it will occupy all the CPU forever, and I have to kill the process to stop it.

dataset = pd.read_csv(dataset_path, encoding = 'GB2312')
dataset['PostCode'].drop_duplicates()

"PostCode" column contains a list of integers but with some "NULL" string, I'm not sure if it's related to column dtype, which for "PostCode" is float64...but the interesting thing is there is another column "AreaCode" which is similar with "PostCode", containing a list of integers and some "NULL", and it works well with drop_duplicates()

Here is my test file download link: 
https://drive.google.com/file/d/0B501Knu4O8vZT1RyampvU2RNTms/view?usp=sharing
Which contains more than 300k rows data

**Comment by shoyer** [comment]
Can you check your memory usage?

I think an infinite loop is unlikely here, but checking for duplicates can take quite a lot of memory which seems a more likely culprit.

**Comment by scratdata** [comment]
The memory looks fine to me, only CPU is 100% occupied.
And I tried to remove the "NULL" string in that column, and then still convert it to float64 dtype, now it works.
So looks like it has nothing to do with float64 type, but related to NaN values.

**Comment by shoyer** [comment]
Hmm. I downloaded your CSV and I can actually run your example just fine on OS X, even on pandas 0.15.0.

Can you share `pd.show_versions()`? How did you install pandas? This might be a sign of a corrupted installation... just a guess.

**Comment by scratdata** [comment]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.8.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-431.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.0
nose: 1.3.4
Cython: 0.21
numpy: 1.8.2
scipy: 0.14.0
statsmodels: None
IPython: 2.3.0
sphinx: None
patsy: None
dateutil: 1.5
pytz: 2014.7
bottleneck: 0.8.0
tables: None
numexpr: 2.2.2
matplotlib: 1.4.1
openpyxl: 2.1.2
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: None

I install it by:
python setup.py build
python setup.py install

And I run my code in a CentOS VM.

**Comment by JacekPliszka** [comment]
Got hit by the same bug.

```
from pandas import read_csv
df = read_csv('sample.csv.gz', na_values=['', ' ', 'null', 'NULL'], sep='|', header=None, names=['a', 'b'])
df.b.drop_duplicates()
```
[sample.csv.gz](https://github.com/pandas-dev/pandas/files/2526340/sample.csv.gz)

**Comment by mroeschke** [comment]
Ideally we would have a self contained example that demonstrates this. Until we do closing for now

**Comment by jacek-pliszka** [comment]
It might have been fixed.

I cannot replicate it any more on Python 3.12 with pandas 1.5.3
