### ISSUE TITLE
BUG/API: interpolate with limit=0 should mean no interpolation

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#9217]
Current behavior:

```
In [28]: s = pd.Series([1, 2, np.nan, np.nan, 5])

In [29]: s
Out[29]:
0     1
1     2
2   NaN
3   NaN
4     5
dtype: float64

In [30]: s.interpolate(limit=0)
Out[30]:
0    1
1    2
2    3
3    4
4    5
dtype: float64
```

But in fact, `limit=0` in contrast to `limit=None` should mean no interpolation.

**Comment by jreback** [comment]
very confusing to have None and 0 mean different things

why would you do this?

**Comment by shoyer** [comment]
I'm testing the results for different interpolation limits and thought a simple way to trigger no interpolation would be use `limit=0`, e.g., `df = pd.DataFrame({lim: s.interpolate(limit=lim) for lim in range(5)})`.

I can see why `limit=None` makes sense as a sentinel value. But I interpreted `limit=0` as "interpolate at most zero values".

**Comment by shoyer** [comment]
Another sane API design would be to disallow `limit=0` entirely, e.g., `assert limit > 0`.

**Comment by jreback** [comment]
ok I understand the reason and it makes sense

though maybe a bit confusing (I get for testing this is useful) but from a user perspective u r like why have an option that makes the function do nothing?

**Comment by jreback** [comment]
yep maybe limit > 0 makes more sense (but raise a ValueError)
