### ISSUE TITLE
BUG: DataFrame constructor incorrect with Series input depending on name

### ISSUE THREAD

**Issue by JohnNapier** [pandas-dev/pandas#9232]
DataFrame constructor example:

``` python
In [55]: x = pd.Series(range(5), name=1)

In [56]: y = pd.Series(range(5), name=0)

In [57]: pd.DataFrame(x, columns=[0])
Out[57]:
Empty DataFrame
Columns: [0]
Index: []

In [58]: pd.DataFrame(x, columns=[1])
Out[58]:
   1
0  0
1  1
2  2
3  3
4  4

```

and for y, the name and columns don't have to match for it to construct.

```
In [59]: pd.DataFrame(y, columns=[0])
Out[59]:
   0
0  0
1  1
2  2
3  3
4  4

In [60]: pd.DataFrame(y, columns=[1])
Out[60]:
   1
0  0
1  1
2  2
3  3
4  4
```

---

Using Pandas 0.15.2-1. After renaming a column in a dataframe, a .join operation fails.

``` python
import numpy as np,pandas as pd
df1=pd.DataFrame(range(1,1001)).rename(columns={0:1})
a=np.log(df1[1])
df2=df1.join(pd.DataFrame(a,columns=[0]))
```

The second column contains all NaN, instead of the values from _a_. The same can be accomplished by other means, but I believe the above should work. For example, the following works:

``` python
df1=pd.DataFrame(range(1,1001))
a=np.log(df1[0])
df2=df1.join(pd.DataFrame(a,columns=[2]))
```

**Comment by TomAugspurger** [comment]
Looks like it's more of an issue w/ the call to the DataFrame constructor. With

```python

In [55]: x = pd.Series(range(5), name=1)

In [56]: y = pd.Series(range(5), name=0)
```

we get

```
In [57]: pd.DataFrame(x, columns=[0])
Out[57]:
Empty DataFrame
Columns: [0]
Index: []

In [58]: pd.DataFrame(x, columns=[1])
Out[58]:
   1
0  0
1  1
2  2
3  3
4  4
```

and for `y`, the name and columns don't have to match for it to construct.

```python
In [59]: pd.DataFrame(y, columns=[0])
Out[59]:
   0
0  0
1  1
2  2
3  3
4  4

In [60]: pd.DataFrame(y, columns=[1])
Out[60]:
   1
0  0
1  1
2  2
3  3
4  4
```

**Comment by JohnNapier** [comment]
Thanks for narrowing the issue to the constructor.

**Comment by TomAugspurger** [comment]
@JohnNapier, I changed the title and added an example to the original post. Let me know if you still have trouble with the join. FYI, the Series method `.to_frame()` should work. I'll work on a fix for the bug.

**Comment by JohnNapier** [comment]
@TomAugspurger, thanks for the help and the tip!

**Comment by dsm054** [comment]
In 0.20.2, this seems to behave the way I'd expect -- constructing a frame with the column name which matches the series gives the same result as to_frame, and using a columns which doesn't match gives us the empty frame.

```
In [102]: len(pd.DataFrame(x, columns=[0])), len(pd.DataFrame(y, columns=[0]))
Out[102]: (0, 5)

In [103]: len(pd.DataFrame(x, columns=[1])), len(pd.DataFrame(y, columns=[1]))
Out[103]: (5, 0)
```

**Comment by jreback** [comment]
yeah I agreee this this seems ok (not sure when was fixed). 

@dsm054 would take some validation tests for this.

**Comment by jreback** [comment]
@dsm054 can you put up a validation test for this?
