### ISSUE TITLE
ENH/DOC: catalog/raise NotImplemented errors for sparse structure methods

### ISSUE THREAD

**Issue by wholmgren** [pandas-dev/pandas#9275]
1. Catalog and document all of the methods that don't currently work on sparse structures.
2. Raise NotImplemented exceptions for these methods.

Would be happy for suggestions for how to do this systematically.

Originally suggested by @jreback  in #9265.

**Comment by jreback** [comment]
@wholmgren thanks for looking at some of this stuff!

**Comment by jreback** [comment]
you might also be interested in a PR about to go in, #9076
