### ISSUE TITLE
Exception in get_group() with invalid index

### ISSUE THREAD

**Issue by danielemichilli** [pandas-dev/pandas#9299]
Hello,

I'm using the pandas function "pandas.core.groupby.GroupBy.get_group()" to parallelize my code.
This function raises a "KeyError" exception if the passed index is not contained in the index list of the grouped DataFrame.

A basic example is:
data = DataFrame({'ind':[0,0,2,2]})
gb=a.groupby('ind')
gb.get_group(1)

Which raises "KeyError: 1"

In order to use intensively the "get_group()" function in code parallelization, an option to avoid this exception would be very useful, similar to "error_bad_lines=False" of the "read_csv()" function.

An empty DataFrame could be returned by the "get_group()" function when this option and an invalid index are given.

**Comment by jreback** [comment]
there was an attempt to do this here: https://github.com/pydata/pandas/pull/5452
welcome to have a pull request along the same lines

**Comment by mroeschke** [comment]
Appears there hasn't been much activity or community support for this feature in a while so closing. Happy to reopen if there's renewed support
