### ISSUE TITLE
ENH date_range yearly frequency flag 'A' is confusing, 'Y' should be accepted

### ISSUE THREAD

**Issue by mangecoeur** [pandas-dev/pandas#9313]
to get a yearly frequency from date range the flag is actually `freq="A"` (for "Annual" i guess) rather than `freq="Y"` for yearly.

It would seem more consistent if it accepted "Y" as well/instead of "A", following the pattern:

hour -> hourly -> H
day -> daily -> D
week -> weekly -> W
year -> yearly -> Y

**Comment by TomAugspurger** [comment]
Anecdotally, I do `freq='Y'` almost every time. Same for resample.

**Comment by imih** [comment]
The referenced issue, https://github.com/pandas-dev/pandas/issues/9312#issuecomment-71404429, concludes `freq=Y` should be an alias for freq='AS'

**Comment by imih** [comment]
Hi, 
The aliases are here:
 https://github.com/pandas-dev/pandas/blob/master/pandas/tseries/frequencies.py#L425

are we fine with `freq='Y'` begin an alias for the beginning of the year while `freq='A'` being an alias for the end of the year? 

Additionally, should other composed freqs containing `'Y'` ( 'BYA', 'BYE', 'YA', 'YE') also be added?

**Comment by jreback** [comment]
so these should following the same convention as Q and M

so Y would be the same as A e.g. end of year and

YS would be year start

**Comment by gfyoung** [comment]
Reopening because the initial PR was incomplete.
