### ISSUE TITLE
ENH date_range should accept dateutil frequency constants

### ISSUE THREAD

**Issue by mangecoeur** [pandas-dev/pandas#9314]
Currently date_range accepts string flags for `freq=`.

dateutil (which is already a pandas dependency) has constants for `YEARLY, MONTHLY, WEEKLY, DAILY, HOURLY, MINUTELY, SECONDLY` which are used in the dateutil equivalent of date_range, `rrule`.

it would be a nice feature if these were accepted as well as the string arguments

**Comment by jcontesti** [comment]
I start to prepare a PR for this enhancement.

**Comment by jorisvandenbossche** [comment]
@mangecoeur since those constants are actually just ints, that means we would effectively also accept ints (of the appropriate range). I am not sure we should do that.

Do you have a good use case for this?

**Comment by mangecoeur** [comment]
@jorisvandenbossche mainly for consistency between using dateutil directly and using it via pandas. I don't think them being ints under the hood is such a big issue (although maybe one day everything will use proper Enums). Anyway, as far as i'm concerned its a nice to have.

**Comment by fpunny** [comment]
take
