### ISSUE TITLE
Panel to_frame should have which axis are columns and index in the new DF

### ISSUE THREAD

**Issue by sirinath** [pandas-dev/pandas#9324]
to_frame should have more control (be explicit) over what axis becomes index and the columns in the DF.

**Comment by sirinath** [comment]
Also to_frame produces a DF which is inconstant with indexing scheme when compared to DF. Minor axis ideally should be the column with item and major axis merged.

**Comment by jreback** [comment]
@sirinath this is long established that a frame in a Panel is essentially a flip of the normal axis (was just originally defined that way). You can certainly swap axes if you need as well. Can you show an API proposal for your first comment?

**Comment by sirinath** [comment]
E.g. `to_frame(['Item', 'Minor'], ['Major'])` or `to_frame(['A', 'B'], ['C'])`

**Comment by jreback** [comment]
closing as Panels are deprecated
