### ISSUE TITLE
Problem mixing datetime64 with other types in DataFrame column

### ISSUE THREAD

**Issue by eoincondron** [pandas-dev/pandas#9336]
Given a DataFrame with a column of type  datetime64, there is a problem assigning values of other types to slice of said column:
    in [148]:

```
import datetime as dt
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random((3, 2)), columns = ['a', 'b' ])
df['c'] = pd.NaT
df.c

Out[148]:
0   NaT
1   NaT
2   NaT
Name: c, dtype: datetime64[ns]
```

It doesn't mind this:

```
In[185]:df.loc[0, 'c'] = pd.datetime.today()
df.c
Out[185]: 
0   2015-01-22 10:56:49.763999
1                          NaT
2                          NaT
```

Now try assigning values of a another type:

```
In [186]: df.loc[0, 'c'] = 1
AttributeError: 'int' object has no attribute 'view'

In[187]: df.loc[[0, 1], 'c'] = 'a', 'b'
AttributeError: 'tuple' object has no attribute 'view'
```

Now, the problem runs deeper than this. I didn't actually come across it when trying to assign mixed types to a single column. I was actually assigning values to a block of a DataFrame which included the time column. Here is an example:

```
In [252]: 
A = pd.DataFrame([[2, pd.datetime(2013, 1, 1)], [3, pd.datetime(2014, 1, 1)]])

In[253]: 
df.loc[[0, 1], ['a', 'c']] = A.values
AttributeError: 'list' object has no attribute 'view'
```

Note that the following works:

```
 In[254]: 
 df.loc[[0, 1], ['a', 'c']] = A
```

So when using the array A.values, the dtype is forced to object which then causes the problem. However, in the case where A has a different index than df, using A.values is necessary to assign the values. Maybe I need to be more careful but the error message doesn't help and it took me a long time to understand the problem. If I try to assign values to a slice of column 'c' using the corresponding slice of A.values I get a different error, which is more informative:

```
In[255]: 
df.loc[[0, 1],  'c'] = A.values[:, 1]
TypeError: Cannot change data-type for object array.
```

**Comment by jreback** [comment]
these could certainly have a trapped (and then better message).

Usually we allow things like this but coerce to ``object``. In general though I think raising is better.
If you really really want say a mixed-dtype Series then one should construct it directly.

Welcome a pull-request to update the errors.

**Comment by jreback** [comment]
this is fixed in master if anyone would like to put up some tests.
