### ISSUE TITLE
Problem indexing into first 2-levels of 3-level Index

### ISSUE THREAD

**Issue by eoincondron** [pandas-dev/pandas#9337]
First create a DataFrame with a 3-level index and then index into it using a single tuple from the outer two levels:

```
import pandas as pd
import itertools
ix = pd.MultiIndex.from_product([range(3), pd.date_range('20140101', '20140102'), list('ab')])
df = pd.DataFrame(0, index = ix, columns = ['A', 'B'])
outer_levels = ix.droplevel(2).tolist()
df.loc[outer_levels[0]]
    A   B
a   0   0
b   0   0
```

No problems there. Now try the whole outer level:

   df.loc[outer_levels]

```
(0, 2014-01-01 00:00:00)    NaN NaN
(0, 2014-01-01 00:00:00)    NaN NaN
(0, 2014-01-02 00:00:00)    NaN NaN
......
```

Or a slice: 

```
df.loc[outer_levels[2:4]].count().sum()
0
```

The order of the levels (i.e. datatypes) doesn't see to matter:

```
for p in itertools.permutations(range(3)):
   df = pd.DataFrame(0, index = ix.reorder_levels(p), columns = ['A', 'B'])
   outer_levels = df.index.droplevel(2).tolist()
   print test.loc[outer_levels].count().sum()
0
0
.....
```

Also, there is no problem indexing into the two outer levels using the same indexer if the 3rd level is dropped:

```
df.reset_index(2).loc[outer_levels[2:4]]
            level_2 A   B
0   2014-01-02  a   0   0
    2014-01-02  b   0   0
    2014-01-02  a   0   0
    2014-01-02  b   0   0
```

Pandas version is 0.15.2

**Comment by jreback** [comment]
hmm, this might be a but realting to the equalit of the Timestamps when they have frequenices. So will mark as a bug.

**Comment by mroeschke** [comment]
I think this behavior correctly raises now. The original list being used to index the DataFrame does not contain an indicator for the 3rd level which I think is now required. Closing as the expected behavior
