### ISSUE TITLE
to_excel doesn't support dateutil.relativedelta

### ISSUE THREAD

**Issue by scls19fr** [pandas-dev/pandas#9372]
Hello,

to_excel doesn't support `dateutil.relativedelta`

```
import pandas as pd
from dateutil.relativedelta import relativedelta
df = pd.DataFrame([relativedelta(years=2)])
df.to_excel('out.xls')
```

raises `Exception: Unexpected data type <type 'instance'>`

```
df.to_excel('out.xlsx')
```

raises `AttributeError: relativedelta instance has no attribute '__float__'`

Not sure if it's a Pandas issue, an XLS writer issue or a dateutil issue.

**Comment by jorisvandenbossche** [comment]
What do you expect as the result in excel, as I think excel does not have such a datatype? A string representation?

**Comment by scls19fr** [comment]
either `to_csv` returns a string so it could be a string also

**Comment by jorisvandenbossche** [comment]
Related to #8188 (same question, but for lists). There is a PR for that (#9181, although that will not solve this case)

**Comment by scls19fr** [comment]
Maybe by default `to_excel` should raise an error when type is not "known" but an additional flag could be add to save to string.

**Comment by WillAyd** [comment]
I can't reproduce this. issue on master; if you are still seeing feel free to ping and can reopen
