### ISSUE TITLE
precision issue with rolling_std

### ISSUE THREAD

**Issue by leo4183** [pandas-dev/pandas#9420]
i tested `rolling_std` func with some real data (floating number with format x.xx).  For a Series/DataFrame which contains let's say 5 continuous identical rows among several hundreds, the `rolling_std` could return a small number with 10^-7 scale instead exactly zero.  this is probably a known issue which has not been officially documented.  i'm just curious with the reason behind and why the std member func works better.

**Comment by porris1000** [comment]
I did the same tests and i confirm you are right. Pandas & Numpy std function return very different precisions.I think the problem doesn't only happen when there are repeated data, although it always occurs in this case. I only found your comment about this issue and have no idea about the reasons, sorry.

**Comment by kay1793** [comment]
#8424 , #8326

**Comment by mroeschke** [comment]
This may have been fixed by https://github.com/pandas-dev/pandas/pull/18481, but we would need a reproducible example otherwise.

**Comment by pilkibun** [comment]
#27593  reproduces this. I don't think it's a bug. When you calculate the variance for each window in isolation, you can get an exact zero result in such a case. When you do a true rolling window calculation, you'll only get something very small in this case due to floating point issues.
