### ISSUE TITLE
BUG: NotImplementedError not handled correctly

### ISSUE THREAD

**Issue by schryer** [pandas-dev/pandas#9432]
#### Lets make a DataFrame with at least three rows (does not fail when only two rows are present).

`df = pandas.DataFrame([[1], [2], [3]])`
#### Selecting rows using query works as expected:

`selected_df =  df.query('index == [1, 2]')`
#### However, performing traditional indexing fails because Pandas is trying to perform an operation on a NotImplementedError exception object:

`df.index == [1, 2]`

```
/home/david/.virtualenvs/py34/lib/python3.4/site-packages/pandas/core/index.py in wrapper(self, other)
     55         # technically we could support bool dtyped Index
     56         # for now just return the indexing array directly
---> 57         if com.is_bool_dtype(result):
     58             return result
     59         try:

/home/david/.virtualenvs/py34/lib/python3.4/site-packages/pandas/core/common.py in is_bool_dtype(arr_or_dtype)
   2463 
   2464 def is_bool_dtype(arr_or_dtype):
-> 2465     tipo = _get_dtype_type(arr_or_dtype)
   2466     return issubclass(tipo, np.bool_)
   2467 

/home/david/.virtualenvs/py34/lib/python3.4/site-packages/pandas/core/common.py in _get_dtype_type(arr_or_dtype)
   2392     elif isinstance(arr_or_dtype, CategoricalDtype):
   2393         return CategoricalDtypeType
-> 2394     return arr_or_dtype.dtype.type
   2395 
   2396 

AttributeError: 'NotImplementedType' object has no attribute 'dtype'
```

**Comment by jreback** [comment]
``.query()`` is a slightly modified python syntax and allows this,
you should be using 

```
In [19]: df.index.isin([1,2])
Out[19]: array([False,  True,  True], dtype=bool)
```

but I'll buy that the ``NotImplementedError`` should be raised here.

want to do a pull-request?

**Comment by schryer** [comment]
I made a pull request to address this issue:

https://github.com/pydata/pandas/pull/9451

The true problem lies with a nasty numpy bug:
https://github.com/numpy/numpy/issues/2091

This numpy bug is documented in this fix so
that it can be removed when the numpy bug is fixed.

Cheers,
David

**Comment by mroeschke** [comment]
Looks to work on master. And I believe we are testing this case already

```
In [49]: df.index == [1, 2]
    ...:
    ...:
Out[49]: array([False, False, False])
```
