### ISSUE TITLE
DOC: revise read_csv doc-string/io.rst to show CSV quoting mechanism

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9503]
http://stackoverflow.com/questions/28541302/pandas-to-csv-with-quoting-3-quote-nonnumeric-doesnt-work

remove the actual numbers and show the usage of the csv module constants

**Comment by gfyoung** [comment]
Don't the <a href="https://github.com/pydata/pandas/blob/6645b2b11a82343e5f07b15a25a250f411067819/pandas/io/parsers.py#L209">docs</a> put more emphasis on the enums now?  IMO this is not really an issue anymore.

**Comment by jorisvandenbossche** [comment]
Yes, I think this was indeed solved
