### ISSUE TITLE
Support pad/backfill/nearest reindexing even for unsorted indexes by storing a sorted index?

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#9510]
Recently, I've been working on adding a 'nearest' method to reindexing: https://github.com/pydata/pandas/pull/9258

It occurs to me that we could easily extend reindexing/get_indexer methods to work with unordered indexes if we were willing to do a sort operation on the index if necessary. This would probably entail saving the sorted result on the parent index, similarly to how get_indexer is currently supported on MultiIndex by creating a tuple index internally.

I think this would be a nice usability gain over the current implementation, and not be _too_ surprising. Sorting indexes (once) is pretty fast, for anything up to millions of rows.

Thoughts?

**Comment by jreback** [comment]
xref is #3539 

you *could* do this in an index, as we can easily store meta data, but not currently for a column (that would require a meta dict in the BlockManager).

Note have to be sure to invalidate these on any setting operations.

Note that IIRC the index cython object DOES cache these things, e.g. ``is_monotonic``, so not sure how much this would actually change it.

**Comment by mroeschke** [comment]
Looks like this never took off so closing. Can reopen if there's interest
