### ISSUE TITLE
Any plans to support PyPy?

### ISSUE THREAD

**Issue by ionelmc** [pandas-dev/pandas#9532]
I couldn't find any official statement about PyPy support.

**Comment by TomAugspurger** [comment]
It will be a while I'd guess. I'm not following the PyPy project too closely, but last I read they're still working on NumPy support. And from what I recall (could be wrong) C extensions are slow in PyPy (I think they use CFFI for faster calling of C stuff, but that would require work).

**Comment by shoyer** [comment]
In addition to NumPy, Pandas also makes extensive use of Cython to speed up slow calculations. It looks like it's theoretically possible to run Cython extensions with PyPy, but the result may not work well: http://stackoverflow.com/questions/14201555/does-pypy-support-cython-extension

So, at this point, I would say we have no plans to support PyPy. I'm not opposed to it in principle, but it would take quite a lot of work to make this feasible.

**Comment by robert-zaremba** [comment]
Any update here?

**Comment by TomAugspurger** [comment]
Maciej Fijalkowski (on the PyPy team) mentioned recently that they'd have updates on numpypy to share soon.

**Comment by kawing-chiu** [comment]
PyPy2 (not PyPy3 yet) now passes 99% of the tests of the upstream numpy. Mattip of the PyPy team is actively working towards pandas support on PyPy.

**Comment by stoneyv** [comment]
In addition to pypy/rpython there is an implementation of a subset of pandas and a subset of numpy for the Stanford weld runtime named "Grizzly" https://github.com/weld-project/weld#grizzly

**Comment by jreback** [comment]
pandas2 will encompass much of this workflow
e.g. lazy evaluation, high perf with multi cores and out of core evaluation 

coming soon

**Comment by kawing-chiu** [comment]
Anyone who wants to know more about the exact progress on this issue can read [this wiki](https://bitbucket.org/pypy/pypy/wiki/cpyext_2_-_cython_and_pandas#markdown-header-june-3-2017).

**Comment by jreback** [comment]
PyPy has made quite some efforts with pandas is fairly well supported

cc @mattip
