### ISSUE TITLE
ENH/API: DataFrame.unstack() support for dropna and sequentially

### ISSUE THREAD

**Issue by seth-p** [pandas-dev/pandas#9533]
Add `dropna` and `sequentially` parameters to `DataFrame.unstack()`, to match `DataFrame.stack()`. For backwards compatibility, these should default to `dropna=False` and `sequentially=False` -- which are different from the defaults for `DataFrame.stack()`.

**Comment by mroeschke** [comment]
Looks like this feature request hasn't gotten much traction over the years so closing. Happy to reopen if renewed intereset
