### ISSUE TITLE
Asymmetric error bars are not supported for series (only dataframes)

### ISSUE THREAD

**Issue by mizzao** [pandas-dev/pandas#9536]
According to [the documentation](http://pandas-docs.github.io/pandas-docs-travis/visualization.html#plotting-with-error-bars), asymmetric error bars should be able to be passed in to `plot` as an Mx2 array for a `Series` object or a Mx2xN array for a `DataFrame` object.

However, the code only seems to parse this correctly for a `DataFrame`: https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L1338

When passing raw error values as `yerr`, it seems that the first values are used as two-sided error differences, instead of being plotted as raw upper and lower values. Note the symmetric error bars below:

![image](https://cloud.githubusercontent.com/assets/2080084/6335609/b0ad6f62-bb6a-11e4-941e-71154ca48eca.png)

Using the underlying matplotlib function directly yields the expected results, but without the pandas-generated decorations:

![image](https://cloud.githubusercontent.com/assets/2080084/6335591/8a3bd170-bb6a-11e4-8e36-400f86cf6e91.png)

This was originally noted in [this StackOverflow question](http://stackoverflow.com/q/26793758/586086) and I corroborated the other user's experience.

**Comment by ericmjl** [comment]
I am having a similar issue here.

**Comment by TomAugspurger** [comment]
Anyone interested in submitting a fix? I can help you out if you run into trouble.

**Comment by ericmjl** [comment]
I'm happy to try! 

@TomAugspurger: I've been a user of `pandas` for a while, but I think I might need some guidance to the codebase. Would you be kind enough to pinpoint roughly where I should get started?

**Comment by TomAugspurger** [comment]
Thanks!

The plotting code is all in `pandas/tools/plotting.py` The logic for parsing error bars should all be [here](https://github.com/pydata/pandas/blob/master/pandas/tools/plotting.py#L1373) so that's were I'd start.
