### ISSUE TITLE
Microsecond date formatter

### ISSUE THREAD

**Issue by azjps** [pandas-dev/pandas#9592]
When plotting time series after importing pandas, the default locator/formatter do not support microsecond resolution handling although it is available in matplotlib 1.3.0+. Besides backwards compatibility reasons, there might not be any reason anymore to keep around the PandasAutoDateLocator/PandasAutoDateFormatter classes, which were introduced in [this commit](https://github.com/changhiskhan/pandas/commit/d0d15b0fa69a0d464a939b757a104d57fc7b4d58). 

See also [my comment here](https://github.com/pydata/pandas/issues/1599) and [this related issue](https://github.com/pydata/pandas/issues/2579). An example of this is shown in [this notebook](http://nbviewer.ipython.org/github/azjps/matplotlib-tick-formatters/blob/master/notebooks/microsecond_precision.ipynb).

```
pd.show_versions():

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.17.7-el5.ia32e.lime.0
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8

pandas: 0.14.0
nose: 1.3.4
Cython: 0.21
numpy: 1.8.2
scipy: 0.14.0
statsmodels: 0.5.0
IPython: 2.3.0
sphinx: 1.1.3
patsy: 0.3.0
scikits.timeseries: None
dateutil: 2.2
pytz: 2014.4
bottleneck: None
tables: None
numexpr: 2.4
matplotlib: 1.4.0
openpyxl: 1.8.6
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: 3.3.6
bs4: None
html5lib: None
bq: None
apiclient: None
rpy2: 2.4.3
sqlalchemy: None
pymysql: 0.6.2.None
psycopg2: None
```

**Comment by mroeschke** [comment]
Thanks for the suggestion but this issue hasn't gained a lot of interest or traction in many years so closing
