### ISSUE TITLE
API: timeseries accessors naming convention

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9606]
we have a slightly odd naming convention for several index (and .dt) accessors

`dayofweek`
`dayofyear`

(and adding `daysinmonth` in #9605)

so these should prob be `day_of_week` 

we should be able to maintain compat on these and just add the new ones.

**Comment by ApolllonDev** [comment]
Hi, may I work on this issue?

**Comment by ApolllonDev** [comment]
@jreback @TomAugspurger 
Hi, the odd naming convention that is mentioned in this issue still exists on the `master` branch. May I work on this issue?

**Comment by Violet-XiaoWeiHuang** [comment]
Hello @jreback ,
I'm a new comer to Pandas, I notice there're other timeseries accessors like 'weekofyear'. Do you want me to work on it?
Thank you.

**Comment by abhishekmangla** [comment]
take
