### ISSUE TITLE
Please add YAML front matter block support for pandas.io.parsers.read_csv

### ISSUE THREAD

**Issue by jrovegno** [pandas-dev/pandas#9613]
Github show me how cool can be use YAML front matter blocks, and now I want to use them to put metadata in my datasets, this must be the new standard. It's easy, human readable and simple.

File example of the format
https://raw.githubusercontent.com/jrovegno/csvy/master/data.csvy

Regards

Javier

**Comment by jreback** [comment]
is this a defined (meaning regular / standard type of format)? is it always detectable via the '---'?

**Comment by jrovegno** [comment]
I am developing a draft specification of the file format
http://jrovegno.github.io/csvy/

**Comment by jbrockmendel** [comment]
Has this format caught on since the OP?

**Comment by janosh** [comment]
Doesn't seem to have caught on much since 2015 but I think it's a cool idea.

**Comment by mroeschke** [comment]
Thanks for the suggestion, but it looks like this format hasn't taken off and probably not suitable for pandas proper. Ideally, an external library can parse the YAML format into python objects from which `pd.DataFrame` can ingest. Closing.
