### ISSUE TITLE
Add an option to to_html so that index names do not take a row itself. 

### ISSUE THREAD

**Issue by colinfang** [pandas-dev/pandas#9625]
``` python
a = pd.DataFrame({'x': [1,2,3], 'y': [2,3,4]})
a.index.names = ['a']
a.to_html()
```

it looks like

```
  x y
a
0 1 2
1 2 3
2 3 4
```

Can we add an option in `to_html` so that we can achieve the following easily?
For the moment I have to drop the index, and bold the first column via formatter which is not simple.

```
a x y
0 1 2
1 2 3
2 3 4
```

**Comment by attack68** [comment]
this is problematic because in the current format it is ambiguous if the name "a" applies to the index or the colums.

probably nothing to do here. 

a workaround is just to name the name the columns "a" and leave tje index name blank
