### ISSUE TITLE
Raise warning when automatically converting datatypes

### ISSUE THREAD

**Issue by amcpherson** [pandas-dev/pandas#9738]
A frequent bug I end up fixing in my own code when working with integer data results from my data auto converting to float, usually on a merge, reindex, unstack, or pivot.

```
In [6]: df = pd.DataFrame(np.random.randn(5, 5), columns=list('abcde'), dtype=int)

In [7]: df.dtypes
Out[7]:
a    int64
b    int64
c    int64
d    int64
e    int64
dtype: object

In [8]: df.reindex(range(3)).dtypes
Out[8]:
a    int64
b    int64
c    int64
d    int64
e    int64
dtype: object

In [9]: df.reindex(range(6)).dtypes
Out[9]:
a    float64
b    float64
c    float64
d    float64
e    float64
dtype: object
```

As far as I know, there is no way to know whether this has happened without doing additional checks after an operation.... or fixing my code, but that would be much easier if I could catch a warning, since i am often performing a long series of operations and figuring out which one converted everything to float is time consuming.

I would also like to suggest converting to object over converting to float if nans are being produced.  At least types of existing data would be preserved.

(I realize reindex is not the ideal choice since it has fill_value as an argument)

**Comment by shoyer** [comment]
Hmm. I can see some merit in this, but I'm generally not a big fan of warnings.

I believe @jreback has been exploring using dynd to support true integer NA in pandas, which would be the clean solution here.

> I would also like to suggest converting to object over converting to float if nans are being produced. At least types of existing data would be preserved.

I'm afraid this suggestion is a non-starter. Object dtype makes all operations very slow -- all the vectorized speedups of numpy go away.

**Comment by jreback** [comment]
@amcpherson 

yeh I am not a fan of warnings either.
I suppose you could add an option ``warnings.dtypes`` maybe that would do this (and be off by default).

**Comment by amcpherson** [comment]
In general I think pandas takes changing the datatype of a column too lightly.  I agree converting to object is a bad idea, I just think converting int to float is worse.

An optional warning would be very useful, and would have the least impact.

**Comment by jreback** [comment]
@amcpherson datatypes change in intelligent ways. The current implementation of integers cannot support NA, so this is unavoidable ATM. much older versions of pandas and numpy will just silently do things (and not even change the dtype). So you don't lose data. I don't think this is a big deal at all; its a fact of life when performing operations.

A pull-request to implement an optional warning would be ok. To be honest I have not seen a request that pandas 'takes chaning the datatype of a column too lightly'. In fact every issue I have come across (and I have looked at these issues for several years) was exactly the opposite. Users want correctness first, don't want conversion to ``object`` and want operations that just work. An occasional int->float is generally IMHO not a big deal. my 2c. of course. 

If you don't want this type of casting, then a nice solution is to use Categoricals where these types of operations are simply not allowed.

**Comment by amcpherson** [comment]
@jreback I believe you about the general user, perhaps my use cases of pandas as quite niche.  Can you elaborate on what you meant by "add an option `warnings.dtypes`".  I can figure out where the warning would be raised, just not sure how it should be enabled/disabled.  If dynd is to be integrated soon, all this is moot.

**Comment by shoyer** [comment]
@amcpherson take a look at the docs on options: http://pandas.pydata.org/pandas-docs/dev/options.html

**Comment by amcpherson** [comment]
Its been about 2 years since I first posted this and I am still using pandas everywhere in my projects, and still this issue is by far the biggest creator of bugs.  In my projects I use ints exclusively for ordinal data for which categoricals don't make sense (nucleotide position in the genome), indices into other arrays, and foreign keys for other tables.  In these cases I would always prefer an error to a silent conversion to int, as conversion results in an exception downstream.

I will look more into implementing an optional warning I can catch unless anything has changed in the last 2 years.

**Comment by jreback** [comment]
@amcpherson we have have 1800+ issues. Howe shall they prioritize?

you are certainly welcome to submit something if you'd like.

In any event the basic issue, of supporting NaN across all dtypes will be supported in pandas2; but not likely till next year.

**Comment by amcpherson** [comment]
@jreback I understand, meant that comment more as a commitment to do a pull request myself.  Taking a quick look at the code, it doesnt seem trivial.  There seem to be many places where casting occurs.

**Comment by jreback** [comment]
@amcpherson np. yeah this is bit non-trivial to do, esp to get most cases.

**Comment by rhshadrach** [comment]
I'm thinking this is now closable with nullable dtypes.

**Comment by mroeschke** [comment]
Yes this appears to work now with the pandas nullable integer dtype (and I believe has testing), so I think this is safe to close.

```
In [18]: df = pd.DataFrame(np.eye(5), columns=list('abcde'), dtype="Int64")

In [19]: df
Out[19]:
   a  b  c  d  e
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  0  0  0  0  1

In [20]: df.reindex(range(6)).dtypes
Out[20]:
a    Int64
b    Int64
c    Int64
d    Int64
e    Int64
dtype: object
```
