### ISSUE TITLE
False negative on SettingWithCopyWarning

### ISSUE THREAD

**Issue by adamklein** [pandas-dev/pandas#9767]
This is pandas 0.15.2

```
In [1]: from pandas import *

In [2]: df = DataFrame({"A" : [1,2,3,4,5], "B": [3.1, 4, 5, 6, 7]})

In [3]: df[["A", "B"]]["A"] = 5  # no warning - bug?!

In [4]: df
Out[4]:
A    B
0  1  3.1
1  2  4.0
2  3  5.0
3  4  6.0
4  5  7.0

In [5]: df[["A"]]["A"] = 5
C:\Anaconda\Scripts\ipython-script.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
if __name__ == '__main__':
```

**Comment by jorisvandenbossche** [comment]
Confirmed with master

**Comment by jreback** [comment]
hmm, at least ``False Positives`` are over.

**Comment by rosydawn1** [comment]
I am using pandas verion 0.18.0, and I am experiencing a false negative on this issue where the 'assignment' fails.

dfa = DataFrame( numpy.random.rand(4,2) ,columns=['a','b'])
indicesa = dfa.a>.5  
sum indicesa #make sure that some of the numbers were >.5
dfa.loc[indicesa]['b'] = 6  #gives the appropriate warning (the assignment does fail)
indexa = [2,1,0]
dfa.loc[indexa]['b'] = 6  #does not give any warning  (but the assignment does fail)

**Comment by OmerJog** [comment]
This is still an issue in master

**Comment by erfannariman** [comment]
What is the expected behaviour here?

**Comment by bersbersbers** [comment]
Here's another one:

```
import pandas as pd

index = pd.MultiIndex.from_product([["vars"], ["fruit", "color"]])
df = pd.DataFrame([["apple", "green"]], columns=index)

# No warning!
df.vars.color = "red"

# Still green!
print(df)

# No effect, but warning: A value is trying to be set on a copy of a slice ...
df.vars.color[0] = "red"
```

After `df.vars.color = "red"`, color is not set to `"red"`, and there's no warning.
