### ISSUE TITLE
Implement optimized method to select subsets or rows of a DataFrame from groups by rank (-1 -> last) or order statistics

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#978]
Motivated by: http://stackoverflow.com/questions/9850954/pandas-get-most-recent-value-of-a-particular-column-indexed-by-another-column

**Comment by ron819** [comment]
@jreback 
Is this still needed? It's marked for 0.17 which was released on 2015.

**Comment by jreback** [comment]
@ron819 this is not marked for 0.17 at all. the soln which is reasonable is
``df.loc[df.groupby('obj_id').data_date.idxmax(),:]``
