### ISSUE TITLE
ERR: better error reporting for passing list to level grouper on non-MultiIndex

### ISSUE THREAD

**Issue by eXcuvator** [pandas-dev/pandas#9790]
`groupy(level=[0])` doesn't work on a unique index. I guess it is semantics whether one allows not only level=0, but also level=[0], but if not, the error message should be different:

```
df = pd.DataFrame(np.arange(0,9).reshape(3,3))
df.groupby(level=[0])
ValueError: level > 0 only valid with MultiIndex
```

**Comment by ron819** [comment]
Any chance this will be fixed soon?

**Comment by jreback** [comment]
a community pull request would make this happen

**Comment by mroeschke** [comment]
This looks to work on master, as the operation is okay and shouldn't raise and error I suppose. Could use a test.

```
In [72]: df = pd.DataFrame(np.arange(0,9).reshape(3,3))
    ...: df.groupby(level=[0]).mean()
Out[72]:
   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [73]: df = pd.DataFrame(np.arange(0,9).reshape(3,3))
    ...: df.groupby(level=0).mean()
Out[73]:
   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
```
