### ISSUE TITLE
ENH: allow transform to handle differently indexed outputs

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9842]
from [SO](http://stackoverflow.com/questions/29502328/python-pandas-time-series-compare-specific-times/29541467#29541467)

using `transform` to broadcast the result works fine if the index is an `Int64Index` because the input and output are the same. However, if you actually need the index (e.g. in this example we are doing an `.at_time(...)` to lookup a particular value, then broadcasting fails.

I think the way to do this is to define `.at_time` as a transform function to handle this case.

**Comment by mroeschke** [comment]
Guess there hasn't been a lot of interest or traction for this feature, and generally since pandas is getting stricter with apply like functionality probably best to have the indexes align so closing
