### ISSUE TITLE
CLN: blocks, not series, should contain logic for arithmetic

### ISSUE THREAD

**Issue by shoyer** [pandas-dev/pandas#9859]
See discussion here: https://github.com/pydata/pandas/pull/9848#discussion_r28181084

This would likely help clean up some of the Series/DataFrame discrepancies in arithmetic operations (mostly for datetime types).

**Comment by maximilianr** [comment]
Would this also help performance materially, if `DataFrame` ops could iterate over Blocks rather than  Columns?
ref https://github.com/pydata/pandas/issues/11623, https://github.com/pydata/pandas/pull/11618

**Comment by jreback** [comment]
@maximilianr most things are already dispatched already by blocks.

**Comment by maximilianr** [comment]
Ah, fair, cheers. The ones that are applied across columns (which happen to have been the ones I've been using recently), seem to only be `quantile` & `round`. 
(There are others on the `DataFrame` object such as `rank`, but don't iterate over columns in python)

**Comment by jreback** [comment]
yeh round is almost a display thing so doesn't really count (and could be daily broadcast)

quantile is bad impl ATM

**Comment by maximilianr** [comment]
I could do a PR for quantile if it's not too complex - what should that look like? Could it go straight to `np.nanpercentile` [[link](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.nanpercentile.html)]? 
Looking at the current code, it's doing a lot though.
