### ISSUE TITLE
API/ENH: Add axis option to DataFrame.insert

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#9893]
I think it is useful to simply add one row specifying a loc.

**Comment by jreback** [comment]
can you show a full-example of using this?

**Comment by sinhrks** [comment]
Current behavior (insert column):

```
import pandas as pd

df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df
#    A  B
# 0  1  3
# 1  2  4

df.insert(1, 'x', [5, 6])
df
#    A  x  B
# 0  1  5  3
# 1  2  6  4
```

What in my mind is allowing to insert new row via ``insert`` using `axis`.

```
df.insert(1, '3', [0, 0, 0], axis=0)
df
#    A  x  B
# 0  1  5  3
# 3  0  0  0
# 1  2  6  4
```

**Comment by jbrockmendel** [comment]
why can't this be done with df.loc?

**Comment by mroeschke** [comment]
Agreed, I think `loc` is the more idiomatic way of adding a new row.

Since discussion for this feature has seemed to stalled, going to close for now.
