### ISSUE TITLE
groupby().apply(lambda x:x.copy()) raise error.

### ISSUE THREAD

**Issue by ruoyu0088** [pandas-dev/pandas#9946]
```
df = pd.DataFrame({"g":[1, 2, 2, 2], "a":[1, 2, 3, 4], "b":[5, 6, 7, 8]})
df.groupby("g").apply(lambda x:x.copy())
```

raise 

```
ValueError: Shape of passed values is (3, 4), indices imply (3, 2)
```

but `lambda x:x` or `lambda x:x[:]` works.

**Comment by ruoyu0088** [comment]
I debuged this and found the different between `df.copy()` and `df[:]`:

```
import pandas as pd
import numpy as np

def f1(x):
    return x.copy()

def f2(x):
    return x[:]

df = pd.DataFrame({"g":[1, 2, 2, 2], "a":[1, 2, 3, 4], "b":[5, 6, 7, 8]})

print f1(df).index._id is df.index._id  #True
print f2(df).index._id is df.index._id  #False
```
although `df.copy().index` is not `df.index`, the `_id` attribute is the same. 

```
(df1, df2), _ = pd.lib.apply_frame_axis0(df, f1, [1, 2], np.array([0, 1], np.int64), np.array([1, 4], np.int64))
print df1.index._id is df2.index._id #True
```

the `apply()` calls `apply_frame_axis0()` to do the job, the index of the result DataFrames share the same `_id` object. This will cause `concat()` raise the `ValueError: Shape of passed values is (3, 4), indices imply (3, 2)` error.

**Comment by jreback** [comment]
you mentioned this in #9867  but we'll take this as a bug-report.

Yes these should do the same.

The entire point of the inference is to guess whether the user is mutating the input or not. IMHO this should be banned, but that ship has sailed.

**Comment by jorisvandenbossche** [comment]
So this doesn't raise an error anymore on master, but you still get an inconsistent output:

```
In [111]: df = pd.DataFrame({"g":[1, 2, 1, 2], "a":[1, 2, 3, 4], "b":[5, 6, 7, 8]})

In [112]: df.groupby("g").apply(lambda x:x)
Out[112]: 
   a  b  g
0  1  5  1
1  2  6  2
2  3  7  1
3  4  8  2

In [113]: df.groupby("g").apply(lambda x:x.copy())
Out[113]: 
     a  b  g
g           
1 0  1  5  1
  2  3  7  1
2 1  2  6  2
  3  4  8  2
```

**Comment by mroeschke** [comment]
close in favor of #14927?

**Comment by jorisvandenbossche** [comment]
Yep
