### ISSUE TITLE
DOC: Comparison with Spark DataFrame

### ISSUE THREAD

**Issue by sinhrks** [pandas-dev/pandas#9982]
It may be nice to have a doc like "Comparison with R / SQL"?
- https://databricks.com/blog/2015/02/17/introducing-dataframes-in-spark-for-large-scale-data-science.html

**Comment by MarcoGorelli** [comment]
closing as there's been no interest in this in nearly a decade

having said that, PRs to improve docs are usually welcome, if someone wants to write this and contribute it, that's fine, but let's close for now to attempt to keep the queue down
